PRAGMA foreign_keys = ON

CREATE TABLE TEAM (
	name TINYTEXT PRIMARY KEY,
	seed TINYINT UNSINGED,
	wins TINYINT UNSIGNED,
	placement TINYTEXT,
	CONSTRAINT CHK_TEAM CHECK (0 < seed < 17 AND wins < 7)
);



CREATE TABLE GAME (
	bracket_position TINYINT UNSIGNED PRIMARY KEY CHECK (0 <= bracket_position <= 62),
	team1 TINYTEXT NOT NULL,
	team2 TINYTEXT NOT NULL,
	score1 TINYINT UNSIGNED NOT NULL,
	score2 TINYINT UNSIGNED NOT NULL,
	winner BIT NOT NULL,
	CONSTRAINT FK_GAME_TEAM_1 FOREIGN KEY (team1) REFERENCES TEAM(name),
	CONSTRAINT FK_GAME_TEAM_2 FOREIGN KEY (team2) REFERENCES TEAM(name),
	CONSTRAINT CHK_GAME CHECK (0 <= bracket_position <= 62)
);



CREATE TABLE BRACKET (
	spot TINYINT UNSIGNED PRIMARY KEY,
	team_name TINYTEXT NOT NULL,
	CONSTRAINT FK_BRACKET_TEAM FOREIGN KEY (team_name) REFERENCES TEAM(name),
	CONSTRAINT CHK_BRACKET CHECK (spot < 127)
);



INSERT INTO GAME VALUES (0, 'Duke', 'Wisconsin', 68, 63, 'Duke')
INSERT INTO BRACKET VALUES (0, 'Duke')
INSERT INTO TEAM VALUES ('Duke', NULL, NULL, NULL)


TRUNCATE TABLE BRACKET
DELETE FROM TEAM
DELETE FROM GAME
DELETE FROM BRACKET
SELECT * FROM TEAM
SELECT * FROM GAME
SELECT * FROM BRACKET

DROP TABLE TEAM
DROP TABLE GAME
DROP TABLE BRACKET


UPDATE TEAM SET seed = 1, wins = 5, placement = 'Final Four' WHERE name = 'Duke'


COMMIT
